### ISSUE TITLE
Refactor Policy Verification

### ISSUE THREAD

**Issue by ChaosInTheCRD** [in-toto/go-witness#125]
Currently, the [policy signature verification in `Verify.go`](https://github.com/in-toto/go-witness/blob/0aaf29b4d0dbd0ce2728d9538a133222a1d17573/verify.go#L79-L81) is handled somewhat differently to how the policy itself is verified. While this makes sense to a degree (verifying policy signatures does not currently support the same amount of signing methods), we should probably refactor the code to reduce repetition and avoid drift between the two verification mechanisms.

**Comment by matglas** [comment]
@ChaosInTheCRD with the MR being merged is this issue completed?

**Comment by ChaosInTheCRD** [comment]
Yes! sorry for leaving this lying around
