### ISSUE TITLE
Issue and pull request template

### ISSUE THREAD

**Issue by matglas** [in-toto/go-witness#227]
I noticed that the in-toto/witness project had a nice issue and PR template set. Would it be wise to copy those over to the in-toto/go-witness project too? If thats helpful I can create a PR for it.

**Comment by matglas** [comment]
@jkjell this could be a good first issue. Could you label it?

**Comment by DarikshaAnsari** [comment]
@matglas Can I work on this issue??

**Comment by matglas** [comment]
Thanks for the contribution.
